const EVENTOS = {
    ACE: 1,
    DOBLE_FALTA: 2,
    PRIMER_SAQUE: 3,
    GANADOS_PRIMER_SAQUE: 4,
    GANADOS_SEGUNDO_SAQUE: 5,
    GANADOS_PRIMERA_DEVOLUCION: 6,
    GANADOS_SEGUNDA_DEVOLUCION: 7,
    WINNER: 8,
    ERROR_NO_FORZADO:9,
    ERROR_FORZADO:10,
    PUNTO_SAQUE:11,
    PUNTO_RESTO:12,
    JUEGO_SAQUE_GANADO:13,
    JUEGO_RESTO_GANADO:14
};

module.exports = EVENTOS;
